version: "3"
services:
  reverseproxy:
    build:
      context: ../nginx
    image: ahmedhosam/reverseproxy 
  backend_user:
    build:
      context: ../udacity-c3-restapi-user
    image: ahmedhosam/udacity-restapi-user
  backend_feed:
    build:
      context: ../udacity-c3-restapi-feed  
    image: ahmedhosam/udacity-restapi-feed
  frontend:
    build:
      context: ../udacity-c3-frontend  
    image: ahmedhosam/udacity-frontend